# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        version: ['3.6', '3.7', '3.8']
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        sudo apt -y install binutils
        python -m pip install --upgrade pip
        pip3 install python-appimage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build AppImage using @niess python-appimage
      run: |
        sed -i "s,pyappimage,$(realpath .),g" appimage/requirements.txt
        python3 -m python_appimage build app appimage -p ${{ matrix.version }}
        ls
        chmod +x pyappimage-x86_64.AppImage
        ./pyappimage-x86_64.AppImage --appimage-extract
        rm -r pyappimage-x86_64.AppImage
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        cp -L /opt/hostedtoolcache/Python/3.*/x64/lib/libpython${{ matrix.version }}*m.so squashfs-root/opt/python*/lib/. | true
        [ -f /opt/hostedtoolcache/Python/3.*/x64/lib/libpython3.8.so.1.0 ] && cp -L /opt/hostedtoolcache/Python/3.*/x64/lib/libpython3.8.so.1.0 squashfs-root/usr/lib/.
        cp -L `which objdump` squashfs-root/usr/bin/.
        cp -L `which strip` squashfs-root/usr/bin/.
        cp -L /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so squashfs-root/usr/lib/.
        cp -L /usr/lib/x86_64-linux-gnu/libopcodes-2.26.1-system.so squashfs-root/usr/lib/.
        echo "Bundling AppImage Tool"
        ARCH=x86_64 ./appimagetool-x86_64.AppImage squashfs-root -n -u 'gh-releases-zsync|srevinsaju|pyappimage|continuous|pyappimage-${{ matrix.version }}*.AppImage.zsync' pyappimage-${{ matrix.version }}-x86_64.AppImage
        mkdir dist
        echo "Moving"
        mv pyappimage*.AppImage* dist/.
        

    - name: Upload Appimage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: pyappimage-${{ matrix.version }}-continuous-x86_64.AppImage
        path: 'dist/'

  Release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: pyappimage-3.6-continuous-x86_64.AppImage

    - uses: actions/download-artifact@v1
      with:                 
        name: pyappimage-3.7-continuous-x86_64.AppImage

    - uses: actions/download-artifact@v1
      with:                 
        name: pyappimage-3.8-continuous-x86_64.AppImage
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        automatic_release_tag: continuous
        title: Beta AppImage Release
        prerelease: false
        files: |
          pyappimage-3.6-continuous-x86_64.AppImage
          pyappimage-3.7-continuous-x86_64.AppImage
          pyappimage-3.8-continuous-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}
